name: club_model
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ####################
  # Utils #
  ####################
  connectivity_plus: ^3.0.6
  equatable: ^2.0.5
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7

  ####################
  # State management #
  ####################
  provider: ^6.0.5

  ####################
  # Offline Database #
  ####################
  hive: ^2.2.3

  #######
  # UI #
  #######
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  material_design_icons_flutter: ^6.0.7096
  flutter_spinkit: ^5.2.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^2.0.0
  fluttertoast: ^8.2.1
  top_snackbar_flutter: ^3.0.0+1

  ####################
  # Firebase #
  ####################
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2 # authentication
  cloud_firestore: ^4.5.3 # firestore database
  firebase_messaging: ^14.4.1 # notifications
  firebase_analytics: ^10.2.1 # analytics
  firebase_crashlytics: ^3.1.2 # crashlytics
  firebase_dynamic_links: ^5.1.1 # dynamic links

  ####################
  # Api Operations #
  ####################
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
